# Generated by Django 4.2.1 on 2023-06-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('revenue', models.FloatField()),
                ('current_price', models.FloatField()),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('measure', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CostsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('F', 'Fixed'), ('V', 'Variable')], max_length=1)),
                ('cost_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.costs')),
                ('supply_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.supplies')),
            ],
        ),
        migrations.AddField(
            model_name='costs',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.products'),
        ),
    ]
