# Generated by Django 4.2.1 on 2023-12-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='measure_units',
            field=models.CharField(default='GR', max_length=10),
        ),
        migrations.AddField(
            model_name='costs',
            name='production_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplies',
            name='measure_units',
            field=models.CharField(default='GR', max_length=10),
        ),
        migrations.AlterField(
            model_name='costsdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
