# Generated by Django 4.2.1 on 2023-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0002_adding_cost_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ref_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
