# Generated by Django 4.2.1 on 2024-01-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0003_adding_ref_id_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ticket_number', models.CharField(max_length=250)),
                ('provider', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=1000)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
