# Generated by Django 4.2.1 on 2024-07-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0004_create_compras_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('unidad_medida', models.FloatField()),
                ('cantidad', models.CharField(default='GR', max_length=10)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=250)),
                ('ref_id', models.CharField(max_length=250, null=True)),
                ('ganancia', models.FloatField()),
                ('precio_actual', models.FloatField()),
                ('unidad_medida', models.CharField(default='GR', max_length=10)),
                ('lote_produccion', models.IntegerField()),
                ('tiempo_produccion', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='costs',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='costos.products'),
        ),
        migrations.AlterField(
            model_name='costsdetails',
            name='cost_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='costos.costs'),
        ),
        migrations.AlterField(
            model_name='costsdetails',
            name='supply_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='costos.supplies'),
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='costos.insumos')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='costos.productos')),
            ],
        ),
    ]
