# Generated by Django 4.2.1 on 2024-07-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0006_insumos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='unidad_medida',
            field=models.CharField(default='GR', max_length=10),
        ),
    ]
