# Generated by Django 4.2.1 on 2024-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0007_alter_insumos_cantidad_alter_insumos_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
