# Generated by Django 4.2.1 on 2024-07-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0009_alter_productos_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costos',
            old_name='insumo_id',
            new_name='insumo',
        ),
        migrations.RenameField(
            model_name='costos',
            old_name='product_id',
            new_name='product',
        ),
    ]
