# Generated by Django 4.2.1 on 2024-07-23 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0010_rename_insumo_id_costos_insumo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costos',
            old_name='product',
            new_name='producto',
        ),
    ]
