# Generated by Django 4.2.1 on 2024-07-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0011_rename_product_costos_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='ganancia',
            new_name='utilidad',
        ),
    ]
