# Generated by Django 4.2.1 on 2024-07-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0012_rename_ganancia_productos_utilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('responsable', models.CharField(max_length=50)),
                ('s01_lunes_plan', models.IntegerField(default=0)),
                ('s01_lunes_real', models.IntegerField(default=0)),
                ('s01_martes_plan', models.IntegerField(default=0)),
                ('s01_martes_real', models.IntegerField(default=0)),
                ('s01_miercoles_plan', models.IntegerField(default=0)),
                ('s01_miercoles_real', models.IntegerField(default=0)),
                ('s01_jueves_plan', models.IntegerField(default=0)),
                ('s01_jueves_real', models.IntegerField(default=0)),
                ('s01_viernes_plan', models.IntegerField(default=0)),
                ('s01_viernes_real', models.IntegerField(default=0)),
                ('s01_sabado_plan', models.IntegerField(default=0)),
                ('s01_sabado_real', models.IntegerField(default=0)),
                ('s02_lunes_plan', models.IntegerField(default=0)),
                ('s02_lunes_real', models.IntegerField(default=0)),
                ('s02_martes_plan', models.IntegerField(default=0)),
                ('s02_martes_real', models.IntegerField(default=0)),
                ('s02_miercoles_plan', models.IntegerField(default=0)),
                ('s02_miercoles_real', models.IntegerField(default=0)),
                ('s02_jueves_plan', models.IntegerField(default=0)),
                ('s02_jueves_real', models.IntegerField(default=0)),
                ('s02_viernes_plan', models.IntegerField(default=0)),
                ('s02_viernes_real', models.IntegerField(default=0)),
                ('s02_sabado_plan', models.IntegerField(default=0)),
                ('s02_sabado_real', models.IntegerField(default=0)),
                ('s03_lunes_plan', models.IntegerField(default=0)),
                ('s03_lunes_real', models.IntegerField(default=0)),
                ('s03_martes_plan', models.IntegerField(default=0)),
                ('s03_martes_real', models.IntegerField(default=0)),
                ('s03_miercoles_plan', models.IntegerField(default=0)),
                ('s03_miercoles_real', models.IntegerField(default=0)),
                ('s03_jueves_plan', models.IntegerField(default=0)),
                ('s03_jueves_real', models.IntegerField(default=0)),
                ('s03_viernes_plan', models.IntegerField(default=0)),
                ('s03_viernes_real', models.IntegerField(default=0)),
                ('s03_sabado_plan', models.IntegerField(default=0)),
                ('s03_sabado_real', models.IntegerField(default=0)),
                ('s04_lunes_plan', models.IntegerField(default=0)),
                ('s04_lunes_real', models.IntegerField(default=0)),
                ('s04_martes_plan', models.IntegerField(default=0)),
                ('s04_martes_real', models.IntegerField(default=0)),
                ('s04_miercoles_plan', models.IntegerField(default=0)),
                ('s04_miercoles_real', models.IntegerField(default=0)),
                ('s04_jueves_plan', models.IntegerField(default=0)),
                ('s04_jueves_real', models.IntegerField(default=0)),
                ('s04_viernes_plan', models.IntegerField(default=0)),
                ('s04_viernes_real', models.IntegerField(default=0)),
                ('s04_sabado_plan', models.IntegerField(default=0)),
                ('s04_sabado_real', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='costos.productos')),
            ],
        ),
    ]
