# Generated by Django 4.2.1 on 2024-07-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0013_programacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='producto_nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
