# Generated by Django 4.2.1 on 2024-07-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0014_planificacion_programacion_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='costos.productos'),
        ),
    ]
