# Generated by Django 4.2.1 on 2024-08-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0016_clientes_planificacion_remitos_remitodetalles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remitos',
            old_name='fecha_entregado',
            new_name='fecha_despacho',
        ),
        migrations.RenameField(
            model_name='remitos',
            old_name='fecha_pedido',
            new_name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='remitos',
            name='fecha_facturacion',
            field=models.DateTimeField(null=True),
        ),
    ]
