# Generated by Django 4.2.1 on 2024-08-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0019_rename_s01_jueves_plan_programacion_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
