# Generated by Django 4.2.1 on 2024-10-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0022_alter_programacion_plan_alter_programacion_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='responsable',
            field=models.CharField(default='Todos', max_length=50),
        )
    ]
