# Generated by Django 4.2.1 on 2024-10-07 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0023_productos_responsable_alter_remitos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='is_producto',
            field=models.BooleanField(default=True),
        ),
    ]
