# Generated by Django 4.2.1 on 2025-01-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0025_alter_remitos_cliente_productosref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('plan', models.IntegerField(null=True)),
                ('sistema', models.IntegerField(null=True)),
                ('corregido', models.IntegerField(null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='costos.productos')),
            ],
        ),
    ]
