# Generated by Django 4.2.1 on 2025-01-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0026_alter_remitos_cliente_planificacionanual'),
    ]

    operations = [
    ]
