# Generated by Django 4.2.1 on 2025-01-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0027_planificacion2024_alter_remitos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='indice',
            field=models.FloatField(null=True),
        ),
    ]
