# Generated by Django 4.2.1 on 2025-01-05 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0028_planificacion2024_planificacion_indice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
