# Generated by Django 4.2.1 on 2025-01-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0029_planificacion2024_productos_habilitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='prioridad',
            field=models.IntegerField(default=10),
        ),
    ]
