# Generated by Django 4.2.1 on 2025-07-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0030_planificacion2024_productos_prioridad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='costos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('categoria', models.CharField(default='MATERIA_PRIMA', max_length=250)),
                ('tipo_pago', models.CharField(default='CAJA', max_length=250)),
                ('estado', models.CharField(default='PENDIENTE', max_length=250)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='costos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCorrienteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos_aplicados', to='costos.factura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas_aplicadas', to='costos.pago')),
            ],
        ),
    ]
