# Generated by Django 4.2.1 on 2025-07-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0031_planificacion2024_proveedor_alter_remitos_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='observaciones',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
