# Generated by Django 4.2.1 on 2025-07-07 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0032_planificacion2024_factura_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='CuentaCorrienteProveedor',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
