# Generated by Django 4.2.1 on 2025-07-07 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0034_planificacion2024_alter_remitos_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorrienteproveedor',
            name='fecha_emision',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
