# Generated by Django 4.2.1 on 2025-07-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0035_planificacion2024_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='caja',
            field=models.CharField(default='VA', max_length=250),
        ),
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='tipo_pago',
            field=models.CharField(default='CUENTA_CORRIENTE', max_length=250),
        ),
        migrations.AlterField(
            model_name='cuentacorrienteproveedor',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='costos.proveedor'),
        ),
    ]
