# Generated by Django 4.2.1 on 2025-07-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0036_planificacion2024_cuentacorrienteproveedor_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorrienteproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='costos.proveedor'),
        ),
    ]
