# Generated by Django 4.2.1 on 2025-07-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0040_planificacion2024_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='content_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
