# Generated by Django 4.2.1 on 2025-07-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0041_planificacion2024_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorrienteproveedor',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
