# Generated by Django 4.2.1 on 2025-07-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0042_planificacion2024_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorrienteProveedorAfect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='costos.cuentacorrienteproveedor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pago', to='costos.cuentacorrienteproveedor')),
            ],
        ),
    ]
