# Generated by Django 4.2.1 on 2025-07-10 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0043_planificacion2024_alter_remitos_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorrienteproveedorafect',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='costos.cuentacorrienteproveedor'),
        ),
        migrations.AlterField(
            model_name='cuentacorrienteproveedorafect',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='costos.cuentacorrienteproveedor'),
        ),
    ]
