# Generated by Django 4.2.1 on 2025-07-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0044_planificacion2024_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='image2',
            field=models.TextField(null=True),
        ),
    ]
