# Generated by Django 4.2.1 on 2025-07-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0045_planificacion2024_cuentacorrienteproveedor_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='importe_pendiente',
            field=models.FloatField(default=0),
        ),
    ]
