# Generated by Django 4.2.1 on 2025-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0046_planificacion2024_alter_remitos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorrienteproveedor',
            name='importe_pendiente',
            field=models.FloatField(default=0, null=True),
        ),
    ]
